const section=document.querySelector('.cinema-scroll'),root=document.documentElement,reduceMotion=matchMedia('(prefers-reduced-motion: reduce)'),track=document.querySelector('.sights-track'),controls=document.querySelector('.sights-controls'),prev=document.querySelector('.sight-prev'),next=document.querySelector('.sight-next'),tableBody=document.getElementById('table');
let targetMouseX=0,targetMouseY=0,mouseX=0,mouseY=0,targetScroll=0,smoothScroll=0,initialized=false,rafPending=false,sightCards=[...document.querySelectorAll('.sight-card')],activeSight=0;
const clamp=(v,min=0,max=1)=>Math.min(max,Math.max(min,v)),smoothstep=(a,b,v)=>{const x=clamp((v-a)/(b-a));return x*x*(3-2*x)},lerp=(a,b,t)=>a+(b-a)*t,segment=(s,a,b,c,d)=>{const enter=smoothstep(a,b,s),exit=smoothstep(c,d,s);return{enter,exit,active:enter*(1-exit)}};
const getScrollDistance=()=>clamp(-section.getBoundingClientRect().top,0,section.offsetHeight-innerHeight);
function set(n,v){root.style.setProperty(n,typeof v==='number'?v.toFixed(4):v)}
function requestFrame(){if(!rafPending){rafPending=true;requestAnimationFrame(update)}}
function update(){rafPending=false;targetScroll=getScrollDistance();if(!initialized||reduceMotion.matches){smoothScroll=targetScroll;initialized=true}else smoothScroll=lerp(smoothScroll,targetScroll,.14);mouseX=lerp(mouseX,targetMouseX,.12);mouseY=lerp(mouseY,targetMouseY,.12);
const f2=segment(smoothScroll,560,900,1300,1620),f3=segment(smoothScroll,1760,2140,2540,2700),progress=clamp(smoothScroll/2700),introExit=smoothstep(90,650,smoothScroll),sEnterRaw=smoothstep(2760,3560,smoothScroll),sEnter=Math.pow(sEnterRaw,1.55),controlsEnter=smoothstep(3360,3660,smoothScroll),blur=clamp(f2.active+f3.active),split=Math.pow(f2.enter,1.5),backScale=.76+progress*.2+f2.enter*.18+f3.enter*.16;
set('--back-opacity',1-f2.active*.06);set('--back-x',mouseX*-12+'px');set('--back-y',mouseY*-4+'px');set('--back-scale',backScale);set('--four-y',10+progress*10+'vh');set('--four-scale',.78+progress*.16);set('--bazaar-y',20-progress*8+'vh');set('--blur-px',blur*14+'px');set('--back-brightness',1-blur*.255);set('--bazaar-blur-px',f2.active*14+'px');set('--bazaar-brightness',1-f2.active*.255-f3.active*.06);set('--bazaar-saturation',1+f3.active*.18);set('--shade-z',f2.active>.02?'2':'0');set('--shade-top-alpha',blur*.465);set('--shade-mid-alpha',blur*.42);set('--shade-bottom-alpha',blur*.51);set('--title-y',introExit*-210+'px');set('--title-scale',1-introExit*.08);set('--title-opacity',1-introExit);
set('--bridge-x','calc(-50% + '+mouseX*18+'px)');set('--bridge-y',mouseY*8+progress*-74-f2.exit*760+'px');set('--bridge-bottom',5-f2.enter*13+'vh');set('--bridge-width',67.2+f2.enter*37.8+'vw');set('--bridge-scale',1.02+progress*.23+f2.exit*.46);
set('--split-left-x','calc(-50% + '+(-split*46)+'vw + '+mouseX*22+'px)');set('--split-left-y',mouseY*10+progress*-74-split*180+'px');set('--split-left-scale',1+progress*.23+f2.enter*.74);set('--split-right-x','calc(-50% + '+(split*46)+'vw + '+mouseX*22+'px)');set('--split-right-y',mouseY*10+progress*-74-split*180+'px');set('--split-right-scale',1+progress*.23+f2.enter*.74);
set('--frame2-opacity',f2.active*(1-f3.enter));set('--frame2-x','calc(-50% + '+mouseX*10+'px)');set('--frame2-y','calc(-50% + '+(mouseY*8-f2.exit*150)+'px)');set('--frame2-scale',1.06+f2.enter*.08+f2.exit*.08);set('--intro-copy-y',introExit*90+'px');set('--intro-copy-opacity',1-introExit);set('--panel2-opacity',f2.active*(1-f2.exit));set('--panel2-y','calc(-50% + '+(-f2.exit*86+(1-f2.enter)*58)+'px)');set('--panel3-opacity',f3.active*(1-f3.exit));set('--panel3-y','calc(-50% + '+(-f3.exit*86+(1-f3.enter)*58)+'px)');
const top=Math.min(220,Math.max(112,innerHeight*.19))-50,parent=innerHeight-(innerHeight-top)/backScale;set('--sights-enter-x',(1-sEnter)*420+'vw');set('--sights-y',(1-sEnter)*Math.max(0,parent-top)+'px');set('--sights-top',parent+'px');set('--sights-screen-top',top+'px');set('--sights-controls-opacity',controlsEnter);set('--sights-visibility',sEnterRaw>.001?'visible':'hidden');controls.classList.toggle('is-ready',controlsEnter>.98);
if(Math.abs(smoothScroll-targetScroll)>.01||Math.abs(mouseX-targetMouseX)>.001||Math.abs(mouseY-targetMouseY)>.001)requestFrame()}
function moveSight(d){activeSight=(activeSight+d+sightCards.length)%sightCards.length;const c=sightCards[activeSight],gap=parseFloat(getComputedStyle(track).gap)||0;root.style.setProperty('--sights-shift',-(c.offsetLeft-gap)+'px')}
prev.addEventListener('click',()=>moveSight(-1));next.addEventListener('click',()=>moveSight(1));
fetch('data.json').then(r=>r.json()).then(teams=>{teams.sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf||a.team.localeCompare(b.team));tableBody.innerHTML=teams.map((t,i)=>{const seq=[...Array(t.w).fill('W'),...Array(t.d).fill('D'),...Array(t.l).fill('L')].slice(-5);while(seq.length<5)seq.push('-');const form=seq.map(x=>'<b class="'+(x==='W'?'win':x==='D'?'draw':x==='L'?'loss':'none')+'">'+(x==='W'?'✓':x==='D'?'–':x==='L'?'×':'·')+'</b>').join('');return '<tr class="'+(i===0?'first':'')+'"><td>'+(i+1)+'</td><td class="club"><span class="badge">'+t.team.slice(0,2)+'</span>'+t.team+'</td><td>'+t.p+'</td><td>'+t.w+'</td><td>'+t.d+'</td><td>'+t.l+'</td><td>'+t.gf+'</td><td>'+t.ga+'</td><td>'+t.gd+'</td><td class="points">'+t.pts+'</td><td><div class="form">'+form+'</div></td></tr>'}).join('')}).catch(()=>tableBody.innerHTML='<tr><td colspan="11">Unable to load standings.</td></tr>');
addEventListener('scroll',requestFrame,{passive:true});addEventListener('resize',requestFrame);addEventListener('pointermove',e=>{targetMouseX=(e.clientX/innerWidth-.5)*2;targetMouseY=(e.clientY/innerHeight-.5)*2;requestFrame()},{passive:true});requestFrame();