const section=document.querySelector('.cinema-scroll'),root=document.documentElement,track=document.querySelector('.sights-track'),controls=document.querySelector('.sights-controls'),prev=document.querySelector('.sight-prev'),next=document.querySelector('.sight-next'),tableBody=document.getElementById('table');
let tx=0,ty=0,mx=0,my=0,raf=0,active=0;const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ss=(a,b,v)=>{let x=clamp((v-a)/(b-a));return x*x*(3-2*x)},lerp=(a,b,t)=>a+(b-a)*t,seg=(s,a,b,c,d)=>{let en=ss(a,b,s),ex=ss(c,d,s);return{en,ex,on:en*(1-ex)}},set=(n,v)=>root.style.setProperty(n,typeof v==="number"?v.toFixed(4):v);
function tick(){raf=0;const s=clamp(-section.getBoundingClientRect().top,0,section.offsetHeight-innerHeight);mx=lerp(mx,tx,.12);my=lerp(my,ty,.12);
const f2=seg(s,560,900,1300,1620),f3=seg(s,1760,2140,2540,2700),cards=ss(2760,3560,s),cardsExit=ss(3560,3700,s),p=clamp(s/2700),intro=ss(90,650,s),blur=clamp(f2.on+f3.on);
set('--back-opacity',1-f2.on*.06);set('--back-x',mx*-12+'px');set('--back-y',my*-4+'px');set('--back-scale',.76+p*.2+f2.en*.18+f3.en*.16);set('--four-y',10+p*10+'vh');set('--four-scale',.78+p*.16);set('--bazaar-y',20-p*8+'vh');set('--blur-px',blur*14+'px');set('--back-brightness',1-blur*.255);set('--bazaar-blur-px',f2.on*14+'px');set('--bazaar-brightness',1-f2.on*.255-f3.on*.06);set('--bazaar-saturation',1+f3.on*.18);
set('--shade-z',f2.on>.02?'7':'0');set('--shade-top-alpha',blur*.465);set('--shade-mid-alpha',blur*.42);set('--shade-bottom-alpha',blur*.51);set('--title-y',intro*-210+'px');set('--title-scale',1-intro*.08);set('--title-opacity',1-intro);
set('--bridge-x','calc(-50% + '+mx*18+'px)');set('--bridge-y',my*8+p*-74-f2.ex*760+'px');set('--bridge-bottom',5-f2.en*13+'vh');set('--bridge-width',67.2+f2.en*37.8+'vw');set('--bridge-scale',1.02+p*.23+f2.ex*.46);
const split=Math.pow(f2.en,1.5);set('--split-left-x','calc(-50% + '+(-split*46)+'vw + '+mx*22+'px)');set('--split-left-y',my*10+p*-74-split*180+'px');set('--split-left-scale',1+p*.23+f2.en*.74);set('--split-right-x','calc(-50% + '+(split*46)+'vw + '+mx*22+'px)');set('--split-right-y',my*10+p*-74-split*180+'px');set('--split-right-scale',1+p*.23+f2.en*.74);
set('--frame2-opacity',f2.on*(1-f3.en));set('--frame2-x','calc(-50% + '+mx*10+'px)');set('--frame2-y','calc(-50% + '+(my*8-f2.ex*150)+'px)');set('--frame2-scale',1.06+f2.en*.08+f2.ex*.08);
set('--intro-copy-y',intro*90+'px');set('--intro-copy-opacity',1-intro);set('--panel2-opacity',f2.on);set('--panel2-y','calc(-50% + '+(-f2.ex*86+(1-f2.en)*58)+'px)');set('--panel3-opacity',f3.on);set('--panel3-y','calc(-50% + '+(-f3.ex*86+(1-f3.en)*58)+'px)');
const top=Math.min(220,Math.max(112,innerHeight*.19));set('--sights-enter-x',(1-cards)*420+'vw');set('--sights-y',(1-cards)*120+'px');set('--sights-top',top+'px');set('--sights-screen-top',top+'px');set('--sights-controls-opacity',cards*(1-cardsExit));set('--sights-visibility',cards>.001?'visible':'hidden');controls.classList.toggle('is-ready',cards>.98);if(Math.abs(mx-tx)>.001||Math.abs(my-ty)>.001)request()}
function request(){if(!raf)raf=requestAnimationFrame(tick)}
addEventListener('scroll',request,{passive:true});addEventListener('resize',request);addEventListener('pointermove',e=>{tx=(e.clientX/innerWidth-.5)*2;ty=(e.clientY/innerHeight-.5)*2;request()},{passive:true});
function move(d){const cards=[...document.querySelectorAll('.sight-card')];active=(active+d+cards.length)%cards.length;root.style.setProperty('--sights-shift',-cards[active].offsetLeft+'px')}prev.onclick=()=>move(-1);next.onclick=()=>move(1);
fetch('data.json').then(r=>r.json()).then(teams=>{teams.sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf);tableBody.innerHTML=teams.map((t,i)=>{let f=[...Array(t.w).fill('W'),...Array(t.d).fill('D'),...Array(t.l).fill('L')].slice(-5);while(f.length<5)f.push('-');return '<tr class="'+(i===0?'first':'')+'"><td>'+(i+1)+'</td><td class="club"><span class="badge">'+t.team.slice(0,2)+'</span>'+t.team+'</td><td>'+t.p+'</td><td>'+t.w+'</td><td>'+t.d+'</td><td>'+t.l+'</td><td>'+t.gf+'</td><td>'+t.ga+'</td><td>'+t.gd+'</td><td class="points">'+t.pts+'</td><td><div class="form">'+f.map(x=>'<b class="'+(x==='W'?'win':x==='D'?'draw':x==='L'?'loss':'none')+'">'+(x==='W'?'✓':x==='D'?'–':x==='L'?'×':'·')+'</b>').join('')+'</div></td></tr>'}).join('')}).catch(()=>tableBody.innerHTML='<tr><td colspan="11">Unable to load data.json</td></tr>');
request();